language: cpp
compiler:
  - gcc
# git submodules workaround
git:
  submodules: false
# use sed to replace SSH URL with the public URL, then init submodules 
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libpcap-dev linux-headers-3.13.0-36-generic cmake
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
env: BUILD_KERNEL=3.13.0-36-generic
install:
script: ./travis.sh
